name: bettercap
version: '2.17'
summary: 802.11, BLE, 2.4Ghz HID and Ethernet networks reconnaissance and MITM attacks tool.
description: |
  The Swiss Army knife for 802.11, BLE, 2.4Ghz HID and Ethernet networks reconnaissance and MITM attacks.
grade: stable
confinement: strict
base: core18
parts:
  bettercap:
    plugin: go
    source: https://github.com/bettercap/bettercap.git
    go-importpath: github.com/bettercap/bettercap
    build-packages:
      - build-essential
      - libpcap-dev
      - libnetfilter-queue-dev
      - libusb-1.0-0-dev

    stage-packages:
      - libpcap0.8
      - libnfnetlink0
      - libnetfilter-queue1
      - libusb-1.0-0

apps:
  bettercap:
    command: bin/bettercap
    plugs:
      - home
      - network
      - network-bind
      - network-control
      - network-observe
      - netlink-connector
      - netlink-audit
      - bluetooth-control
      - firewall-control
      - x11

      
